import { Inter } from 'next/font/google'
import './globals.scss'
import Navigation from '@/components/navigation.component'
import Footer from '@/components/footer.component'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="stylesheet" href="https://use.typekit.net/hgb8vzb.css"></link>
      <body className={inter.className}>
        <Navigation />
        {children}
        <Footer />
        </body>
    </html>
  )
}
